version: "3"

services:
  postgres:
    image: postgres:16
    volumes:
      - ./db/table.sql:/docker-entrypoint-initdb.d/1.sql
      - ./db/data.sql:/docker-entrypoint-initdb.d/2.sql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=product_db

  nodejs:
    build: ./nodejs
    ports:
      - 3000:3000
    environment:
      - DB_HOST=postgres
      - DB_USER=user
      - DB_PASS=pass
      - DB_NAME=product_db